### ISSUE TITLE
Issues with the previous week

### ISSUE THREAD

**Issue by danjford** [neilgupta/Sherlock#15]
Works: 
`Meeting next monday at 3pm`

![image](https://cloud.githubusercontent.com/assets/7963046/19600644/e0f5fa02-979d-11e6-93c8-8e6142c17864.png)

Fails:
`Meeting last monday at 3pm`

![image](https://cloud.githubusercontent.com/assets/7963046/19600666/f4f24060-979d-11e6-8740-8b3ed7836316.png)

**Comment by neilgupta** [comment]
Good catch! The math for calculating the last weekend was totally wrong, should be fixed now.
