### ISSUE TITLE
Thu is an invalid day

### ISSUE THREAD

**Issue by jayenne** [neilgupta/Sherlock#18]
Firstly... really great work Neil.

I've found a few terms that return false.
thu & thur are not recoginised as thursday where thurs is (and 3 letter terms for all other days.

I also note a couple of terms common in England that would be nice to include are "Thursday week" and "a week next Thursday" both of which mean "not the coming Thursday but the one after that".

kind regards,
Jayenne

**Comment by neilgupta** [comment]
Thanks for the feedback, fixed both issues.
