### ISSUE TITLE
Relative dates

### ISSUE THREAD

**Issue by ncammarata** [neilgupta/Sherlock#23]
Hi Neil,

Awesome work so far! What do you think about having days/weeks/months automatically have an end? For instance, yesterday started at midnight and ended at midnight. I'm doing basic NLP for event filtering, and it would be helpful to have explicit starts and ends when available.

Curious to hear your thoughts!

**Comment by neilgupta** [comment]
You could easily add this functionality for your app via Watson's postprocessor. Something like the following should do what you need:

```javascript
postprocess: function(Sherlocked) {
    if (Sherlocked.isAllDay) {
        if (!Sherlocked.endDate) {
            Sherlocked.endDate = new Date(Sherlocked.startDate);
        }
        Sherlocked.endDate.setHours(23,59,59);
    }
    return Sherlocked;
}
```

**Comment by neilgupta** [comment]
Closing this issue since I think Watson solves the problem sufficiently. Let me know if you disagree!

**Comment by ncammarata** [comment]
Thanks @neilgupta!
