### ISSUE TITLE
`hr` & `hrs` don't work. meanwhile `min`, `mins`, `sec` & `secs` work.

### ISSUE THREAD

**Issue by deadcoder0904** [neilgupta/Sherlock#32]
I just checked the demo site. `hr` & `hrs` don't work. I think it's pretty common :)

**Comment by neilgupta** [comment]
`h` was supported, but I've added support for `hr` and `hrs` as well now 👍

**Comment by deadcoder0904** [comment]
Thank you @neilgupta. I wasn't using this library yet but the app I'm using [Typefully.app](https://typefully.app) used it & it wasn't working on that.

Will definitely be using this thing in my next project. Really cool project 🔥🔥🔥

**Comment by linuz90** [comment]
Hey, Typefully founder here. The npm packed isn't still updated with this right?

**Comment by neilgupta** [comment]
@linuz90 sorry this totally fell off my list. It's a bit late, but just pushed the updated version to npm 👍
