### ISSUE TITLE
Add new localizations

### ISSUE THREAD

**Issue by neilgupta** [neilgupta/Sherlock#5]
Currently, Sherlock only supports US English locale format for times and dates. It would be nice to add support for other formats (UK) or other languages, with an option to pass the desired locale to Sherlock during parse or via Watson.

**Comment by thomasbrunstrom** [comment]
I've made a version which supports localization, don't know if you'd like my implementation and I just made some small updates, so the code isn't really optimized and clean. Do you want med to make a fork so you can look at it?

**Comment by neilgupta** [comment]
That's awesome! You should definitely open a pull request and hopefully we can get it merged :)

**Comment by jbpin** [comment]
Nice job... I'm keen to test that. I can help to make a french version.
